### ISSUE TITLE
Will Microsoft Learn replace MVA?

### ISSUE THREAD

**Issue by MarcoJanse** [MicrosoftDocs/TeamBlogFeedback#130]
Will Microsoft Learn replace the Microsoft Virtual Academy eventually?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26c7d914-e786-d705-977d-4f5fe050f420
* Version Independent ID: 90e0d126-c3ff-00ec-b910-528c64a8c9db
* Content: [Introducing Microsoft.com/Learn](https://docs.microsoft.com/en-us/teamblog/introducing-ms-learn)
* Content Source: [teamblog/introducing-ms-learn.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-ms-learn.md)
* Product: **team-blog**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by samirgunic** [comment]
Good question! The fact is that Microsoft already offers great content for learning. The only problem is that you need to know where to find it. Unfortunately it is all scattered throughout the many websites that Microsoft operates. I for instance thought that Microsoft Virtual Academy (MVA) was gonna be replaced by this new thing called "Microsoft Tech Community" (MTC). In fact, there is plenty of content on MVA that is nothing more than a pointer to content on the new MTC site. And now this! Microsoft Learn (ML) or rather Microsoft Docs Learn (MDL) since operated under the Microsoft Docs umbrella. How do all these things fit together?

**Comment by weitzhandler** [comment]
But will it offer the learning path that MVA used to, for example MEAN Stack web development / Windows Development?
Because it currently only offers individual courses or very limited learning paths.

**Comment by samirgunic** [comment]
Yes, Microsoft Learn (ML) does have paths.

If you go to the front page of [ML](https://docs.microsoft.com/en-us/learn/) and select "Learning paths", you can then select a role like "Windows Developer". That would be the Windows development path.

You will get a query that looks something like this.

`https://docs.microsoft.com/en-us/learn/browse/?roles=developer&products=windows`

Role and product is where it's at.

There is nothing special about the [MEAN path on MVA](https://mva.microsoft.com/learning-path/mean-stack-development-5). It's just a collection of 4 courses spanning 16 hours.

1. MEAN Stack Jump Start
2. Using Node.js with Visual Studio Code
3. Introduction to Angular 2.0
4. MongoDB and Redis Caching

I don't see why Microsoft would not be able to simply move the MVA content they currently have over to ML. I would expect them to do more than that though. As these courses are between 2 to 4 years old they should consider creating brand new courses covering these topics (M, E, A and N). I'm not so sure thought that it's in their best interest to put in the effort and focus on MEAN.

**Comment by samirgunic** [comment]
I have not had time to play around much with ML, and frankly there is not a whole lot of content yet. But I am loving it already. It's a major improvement over MVA in every aspect. I hope this will continue to grow and surpass MVA.

I'm not sure what the end-goal is with ML as Microsoft has so many different sites for learning and professional training and certification. If it's meant to be a one-stop-shop for learning about all things Microsoft (adding certification resources as well), then I think it would make sense to assign it its own sub-domain, i.e. `learn.microsoft.com`. MVA had its own sub-domain for example. Why would ML not get the same treatment?

If you think about it, learning happens in many ways, in many places, including the Docs. If it's meant to be just a simple coding playground, then you might as well just include it in the Docs articles where you see fit, instead of allocating ´docs.microsoft.com/learn´ for this purpose.

Structured learning ("paths" are an example of this) don't mix and match well with documentation. You don't want to create too much noise in the Docs. These are two different kind of entities. It's like comparing a novel to a dictionary.

**Comment by prilcool** [comment]
It would have been good , if at least the section for MVA certificates learning path badges was still available through Microsoft learn just for validation purposes  .

**Comment by weitzhandler** [comment]
Wish ML offered complete learning path forward MCSD etc certificates.

**Comment by mlottner** [comment]
@MarcoJanse Thanks so much for taking the time to share your Microsoft Learn feedback!
I've assigned this issue to the Learn team to answer all of the questions and requests in this thread. 
In the future, make sure to leave feedback and questions in the specific product or page of interest to get the fastest response possible.

**Comment by jeffbarnes769** [comment]
Hi, In the past I earned a number of badges on MVA, and now can no longer find them?  Do they still exist - even if retired?

**Comment by samirgunic** [comment]
> Hi, In the past I earned a number of badges on MVA, and now can no longer find them? Do they still exist - even if retired?

I presume you're referring to the certificates of completion. I'm afraid those are long gone by now.

> "To simplify your tech training journey, we are consolidating our learning resources and retiring Microsoft Virtual Academy in phases, beginning on January 31, 2019. Complete site retirement is scheduled for later in 2019. Check your MVA Dashboard frequently for courses you have started that are retiring. To earn your certificates of completion, be sure to finish any courses by **January 31, 2019**."

This is a paste from an e-mail I received on Mon 1/28/2019.

> "To simplify your tech training journey, we are consolidating our learning resources and retiring Microsoft Virtual Academy in phases, with the next phase finishing on April 30, 2019. On that date, learning paths and associated badging are retiring. Complete site retirement is scheduled for later in 2019. Check your MVA Dashboard frequently for courses you have started that are retiring. To earn your certificates of completion, be sure to finish any courses by **April 30, 2019**."

This is another paste from an e-mail I received on 2/12/2019. As you can see, the final date has been pushed back from January 31 to April 30. That's year 2019, so that's almost a year ago now.

Although it says that you have to "finish any courses" by this date, in order to "earn your certificates of completion". It doesn't exactly say that you can't download the ones you have already earned, or that you won't be able to download them past this date. I think it's presupposed that this applies to all certificates on MVA, old and ones not earned yet at the time of writing. I have personally not visited the site in a very long time, so I would not know for sure. Perhaps there is a hidden mechanism for downloading them even now? Only Microsoft will know that for sure.

**Comment by jeffbarnes769** [comment]
Thanks
I do have some of the certificates of completion downloaded and a
transcript - but was actually talking about badges that were offered for
completing a number of courses together.  If I recall, completing 4 courses
for Big Data; 2 or 3 of IOT...   Looking to see if they are available,
since the links are no longer valid: i..e
https://mva.microsoft.com/RewardEvidence.aspx/?key=06GDi-Dt1zSX41t41_jh1A2
 https://mva.microsoft.com/RewardEvidence.aspx/?key=Fnkm1dCZZBJUzFP3hfoEHw2


[image: image.png]

**Comment by samirgunic** [comment]
I see what you mean now. In a perfect world those would have been transferred to the new site during migration. Microsoft Learn (ML) also has a concept of badges (and trophies), just not the ones you earned at Microsoft Virtual Academy (MVA). I think you will find that equivalent badges are available at ML, but you will be expected to perform some tasks in order to claim them. In contrast with MVA, the new ML site content consists mostly of text and interactive guides that you step through. So you will not find many traces of MVA content at the new ML site.

What was previously found under Accomplishments on MVA is now found under Achievements on ML. You have to sign in with your Microsoft account, go to Microsoft (Docs) Learn and create a public profile with a display name.

![2020-03-01-211247](https://user-images.githubusercontent.com/3742529/75635351-a88b6e00-5c15-11ea-9fe5-f29760e03218.png)
![2020-03-01-211341](https://user-images.githubusercontent.com/3742529/75635352-a9240480-5c15-11ea-988c-674293719dd9.png)
![2020-03-01-211538](https://user-images.githubusercontent.com/3742529/75635353-a9240480-5c15-11ea-9500-1756f6abd64b.png)
![2020-03-01-211752](https://user-images.githubusercontent.com/3742529/75635354-a9240480-5c15-11ea-8c85-9fc2bec90fe2.png)
![2020-03-01-233636](https://user-images.githubusercontent.com/3742529/75635355-a9bc9b00-5c15-11ea-9679-437b947751c2.png)
![2020-03-01-211009](https://user-images.githubusercontent.com/3742529/75635356-aa553180-5c15-11ea-8d4a-f7a556b5753d.png)

To get you started, I have compiled a list of links based on the badges you provided. You can have a look at these if you like to claim new badges on these topics. These may not exactly correspond to the contents of the course you took at MVA. There are many more technologies to explore that go under the terms IoT and Big Data. But this short list should be enough to get you started.

Azure DevOps
https://docs.microsoft.com/en-us/learn/browse/?products=azure-devops&roles=developer

IoT
https://docs.microsoft.com/en-us/learn/browse/?products=azure-iot

IoT Central
https://docs.microsoft.com/en-us/learn/browse/?products=azure-iot-central

IoT Edge
https://docs.microsoft.com/en-us/learn/browse/?products=azure-iot-edge

IoT Hub
https://docs.microsoft.com/en-us/learn/browse/?products=azure-iot-hub

SQL Data Warehouse
https://docs.microsoft.com/en-us/learn/browse/?products=azure-sql-data-warehouse

Data Lake
https://docs.microsoft.com/en-us/learn/browse/?products=azure-data-lake

HDInsight
https://docs.microsoft.com/en-us/learn/browse/?products=azure-hdinsight

For what it's worth, if you would like to revisit the old MVA video content, you will now find it over at Channel9. It seems like all video content has been migrated to Channel9. It would be helpful to know the title of the course you took at MVA, and then just do a search for it on Channel9.

For example, I think "Getting Started with Microsoft Big Data" was an MVA course. You will find the video material here: https://channel9.msdn.com/Series/Get-Started-MS-Big-Data

Although it will not earn you a new badge, the video content on Channel9 is a great learning resource, and Microsoft was smart enough to preserve the MVA video content. I have not had time to browse the library, but it seems to me like all MVA videos are there. I even found some video material by MVA authors that predates MVA, i.e. early versions of the video material before it was published on MVA.

**Comment by jeffbarnes769** [comment]
Thank you very much for the detailed response.  I already have an account on ML, and a couple of courses completed.   What I understand is that links to the previous badges/trophies no longer exist?
 
 _I think you will find that equivalent badges are available at ML, but you will be expected to perform some tasks in order to claim them._
 
To be clear, "some tasks" means to retake the course(s), correct?  There's no 'import previous' option?

**Comment by samirgunic** [comment]
When you put it like that, yes. Although technically it's not so much about retaking the courses, since the new courses don't have a one-on-one correspondence with the new coureses. Well, the new courses are not even courses, they are now called "modules" or "learning paths" rather (where modules serve more like chapters).

Links to previous badges have been invalidated I think. They all just redirect to ML now. At least I have not found a way to import old badges.

These badges (from MVA and ML) are not to be confused with digital badges that are earned as part of a Microsoft certification exam. Those can still be accessed from the "Microsoft Learning" dashboard.

![microsoft-learning](https://user-images.githubusercontent.com/3742529/75724892-9d9d1000-5cdf-11ea-906b-8acc10acd212.png)

https://www.microsoft.com/learning/dashboard

Although these are also being migrated to Microsoft Learn, so "Learning" will eventually become just "Learn".

**Comment by jeffbarnes769** [comment]
Thanks Samir, have my answer. 
Q: Are my previous badges accessible?
A: No, they are not
