### ISSUE TITLE
Error trying to Generate Access Token using oAuth 2.0

### ISSUE THREAD

**Issue by Josemboa** [MicrosoftDocs/TeamBlogFeedback#144]
When I'm trying to Generate Access Token using oAuth 2.0 I got the error below: 
```
This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.
```

I'm using the link [https://ds.kaiza.la/api/Oauth/Authorize?client_id=b19786ca-df0c-4934-99ea-58198836b788&redirect_uri=https://www.getpostman.com/oauth2/callback](url), where the client_id is my Connector ID.

Please see the attached image.
![kaizalaerror](https://user-images.githubusercontent.com/5972884/51110265-b824d900-1800-11e9-977f-52ec19ae9d2c.PNG)

**Comment by mlottner** [comment]
@Josemboa Thanks for taking the time to leave us blog feedback. 
What page of Microsoft docs was this error in reference to? 
In the future, make sure to leave your question, issue or feedback on the specific page you have questions on in order to get the fastest reply possible. 
I'm closing this issue for now, but feel free to open it again if/as needed with additional site feedback.
