### ISSUE TITLE
How can i view my previous comments?

### ISSUE THREAD

**Issue by MTRuchi** [MicrosoftDocs/TeamBlogFeedback#17]
I had asked a question in January/early February on one of the support pages which was answered subsequently by someone from support. I needed to refer to it again, but it is now not there because content has been moved to Github. How can I see the previous comment and solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com | Microsoft Docs](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by MNF** [comment]
A few weeks ago this page mentioned read only archive of old comments? What is progress of it?

**Comment by LordLiverpool2** [comment]
Throwing away all the old comments is vandalism. It means losing lots of valuable information. The justification is what... laziness?

**Comment by ShevaDas** [comment]
Hey everyone, thanks for the feedback. To quote Rob Eisenberg, the driving force behind the feedback system changeover: 

> Please don't assume that the present lack of an archive feature for old comments is any indication that the people who work on this site do not care about you, your feedback, or the valuable information contained within these comments. It's easy to attack "Microsoft", but please remember that this company is made up of many normal people who really do care. Also, we use the same documentation as you :) I personally have been saved by just the right information being present within a comment on an article, so I understand the concern, as do others.

> So, why no archive solution right now? Frankly, it's for the usual reasons that you might expect at a company Microsoft's size. I won't go into details, as that would not be appropriate. Please realize that it's not because of any lack of desire on the part of the people working on this site to "do the right thing". We know this is important and we want your valuable comments to be preserved. 

@MNF is correct—we are looking into creating a read-only anonymized archive of old comments. However, the engineering work needed is significant due to the sheer volume of content, and needs to compete for prioritization against many other critical site changes. That means it may not be completed for some time. I promise you that your voices have been heard and will help us in understanding the priority of this feature.

Thank you for your patience in this matter and for being a part of the community. I hope you find the new feedback system valuable as well!

**Comment by LordLiverpool2** [comment]
There is a difference between the individuals who work at Microsoft, who are caught in the machine, and Microsoft as a whole. Our criticisms are directed at Microsoft as a company. 

Yes, it is easy to criticise Microsoft, because they have form. For example, virtually every link to Microsoft pages you find on the web is broken, because you didn't bother to redirect from the old pages to the new ones when reorganising the siter (which you do frequently). Like the comments problem, this is basic web site management (and I fail to see why it can't be automated; you make it sound as if people will have to transfer the comments one by one). This sort of important bread and butter stuff seems to be ignored in favour of chasing the latest shiny thing, which brings fewer specific benefits to users in the short term. 

If Microsoft (as opposed to its employees) truly valued user comments, they would have postponed the migration to GitHub until the resources had been found to complete the comment migration, too. The fact that this didn't happen speaks volumes about their priorities.

**Comment by ziesemer** [comment]
I am now left scratching my head after having wasted an hour trying to go back and find some past context that was left regarding Azure Automation.  This is important.  I fully support that a change was needed, and that the improvements here are well worthwhile.  However, I agree with @LordLiverpool2 - the migration should have been postponed until there was at least some solution for the comment migration.  Even if not perfect, as long as there was some way to get at the existing data.

How about providing a dump of the anonymized archive?  Even if not immediately integrated, searchable, etc. - those of us with a need to access the old comments would get to what we need, if not have a community-driven effort to provide for a proper search mechanism, etc.?

**Comment by grahambunce** [comment]
@ShevaDas if Microsoft hadn't abandoned "proper" documentation years ago and decided to put "documentation" in the myriad of blogs and articles scattered across the web, only found by someone's ability to optimize a search request, then you wouldn't be in the mess you're in now in that *lots* of useful information is in comments/feedback scattered all over the place. 

You want us (the consumers of your products) to go back to the Dark Ages where we haven't a clue that the bug we found was actually answered *years* ago in some random comment but that we can't find that comment because you've lost it, so we're back to trying to fix the same thing again.

**Comment by dend** [comment]
Hey folks, just a reminder to please keep it civil - we are working on a good solution for archiving past comments. Rest assured that the team is looking into this.

**Comment by MNF** [comment]
@dend, can you start a good solution from changing the banner: explain,that comments will be available, not asking to “help yourself”? And do not migrate to GitHub new areas, until  the solution will be ready.

**Comment by dend** [comment]
@MNF the migration work is happening behind the scenes as we speak - we do not ask customers to export their own comments at this time. The team will follow-up once we have more updates on the progress and availability of content.

**Comment by NightFantomJ2** [comment]
> we do not ask customers to export their own comments at this time

what is this then? [link to example site I happened to have open](https://docs.microsoft.com/en-us/python/api/overview/azure/monitoring?view=azure-python)
![image](https://user-images.githubusercontent.com/7152733/38354495-155fe5d2-38ba-11e8-9ef4-81219aeb6d0f.png)

**Comment by dend** [comment]
@NightFantomJ2 that applies to a single comment thread - if you see some information that is super-important, we recommend you copy-paste it. Otherwise, you should wait for the content export to happen.

**Comment by NightFantomJ2** [comment]
@dend Thanks for clarifying that, I hope you understand my (our?) confusion on the matter however, as it's not worded clearly in that note that the comments are saved.

**Comment by dend** [comment]
@NightFantomJ2 understood. Rest assured that we are actively working on the task.

**Comment by grahambunce** [comment]
What would help is some clarity on basic "help needed questions". For example, "why does the product work this way?"

Is that question product feedback? Well, no... product feedback is changes requested to the product... which points me to User Voice... and don't get me started on how user voice is simply a place where ideas live for years before being looked at, or simply ignored forever.

Is that question documentation feedback? Well, perhaps, is something is missing in the documentation.... but's it's not really a fault and it's not really feedback on the documentation either.

One (only?) advantage of the blog approach is that there was a chance that someone appropriate in Microsoft may be listening and could give you some help. it would be good if that isn't lost in this migration.

**Comment by Dani21** [comment]
@dend As of 3 weeks after your comment, I'm still seeing no clarification on this page for instance: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/copy-item

That said, I'm at least glad something is being done to preserve the value of old comments.

**Comment by matjin** [comment]
https://azure.microsoft.com/en-us/blog/help-improve-our-azure-docs/

Our new prototype tool, Aladdin, indexes some of this comment data. Try it out!

**Comment by ShevaDas** [comment]
Thanks for sharing, @matjin. To clarify, this tool does _not_ replace the plans to create a full public anonymized archive of comments. Our team was recently able to start work on that, and I hope to be able to share a more detailed update soon. :)

**Comment by Claus-Andersen** [comment]
We are now more than 3 months down the road from the original post, and it still in a limbo state. I think we all understand the you guys from MS is working on it AND that there are some reasons that it's not yet ready, but please act and open up for comments on docs again until the new functionality is available!

**Comment by mlottner** [comment]
@shirgoldbird Any updates on this? I'd like to close this thread and move it to site feedback.

**Comment by mlottner** [comment]
Thanks everyone for your feedback and suggestions with regards to how Microsoft handles future site migration and comment archiving. 

We've taken all of your feedback for inclusion in our plans for future upgrades and changes. 

I'm closing this issue for now, but feel free to open new site feedback issues if you need to report additional issues, or offer your suggestions and ideas for other types of improvements. 
Appreciate everyone to took the time to contribute here for the benefit of the entire user community.
