### ISSUE TITLE
page layout

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/TeamBlogFeedback#19]
Given that this site is about documentation, i find pages like this with huge pictures to be very inefficient. They just force me to scroll to get to the content I want to read (I'm not here for the pictures :)).
Pictures should only be included in docs.microsoft.com when they are providing visual information that is necessary to help understand the content, i.e., screen shots and flow charts.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ef5be1-2def-575d-d803-c257bf1314f6
* Version Independent ID: 46f9065d-fa38-15ee-1200-8c16f5fce81a
* Content: [Help make docs.microsoft.com better! | Microsoft Docs](https://docs.microsoft.com/en-us/teamblog/help-make-docs-microsoft-com-better)
* Content Source: [teamblog/help-make-docs-microsoft-com-better.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/help-make-docs-microsoft-com-better.md)
* Service: **unspecified**
* GitHub Login: @dend
* Microsoft Alias: **dend**

**Comment by dend** [comment]
Hi @DeanGross - can you comment on where you see a bad use of pictures?

**Comment by StillLearnin** [comment]
Read the comment again.
> i find pages like this with huge pictures to be very inefficient. 
My gut reaction to this page was similar. Why is there a picture? How does it fit? Oh, presumably it is a developer giving Microsoft some feedback. But it could just as easily be my aunt giving her cousin a tutorial on Facebook.

The picture in this case seems to be filling a purely cosmetic role which is fine for an advertisement but, in my opinion, **not really useful** in documentation. I don't have time to _waste_ parsing unnecessary data.

**Comment by obivon** [comment]
I am also a fan of this docs site in general and would like to see my company deploy something similar.  While I didn't notice the picture at first, I tend to agree with the op.  I didn't notice the pic because my mind is fairly good at ignoring most banner-like graphic content on pages.  The pic in question is clearly for advertisement/mental tone setting, which has some merit.  I just wish it could display all the generally positive messages for which MS posted it without taking up so much space and bandwidth.  

Large graphics on a full-sized, standard monitor are easier to ignore and navigate around than on mobile devices or touchscreens.  I was about to mention the pain of navigating around this large pic on a cell phone but the shape works rather well on my basic iPhone 7.  Congrats on formatting this site well for the devices I've viewed it on and thanks for not making it a link.  Linked ad pics on cell phones are rough some days.  

The picture on this page (https://docs.microsoft.com/en-us/teamblog/help-make-docs-microsoft-com-better) is at least a fairly small amount of data (1.01 MB.)
Even so, at home this picture would take ~3 seconds to download.  Even IT people still sometimes have slow or metered internet connections.   

Please continue keeping the number of blatant ad pics very low on this  site.  

--cheers,
Obivon

**Comment by mlottner** [comment]
@DeanGross @StillLearnin @obivon Thanks for taking the time to give us feedback on visuals. 
Our content guidance remains the same and we aim for minimal graphics use. Graphics are encouraged only when warranted to explain complex ideas or flows. 
I'm closing this issue for now, but feel free to re-open it if/as needed.
