### ISSUE TITLE
Paste Images Not Supported

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/TeamBlogFeedback#2]
One feature I really love about GitHub issues is the ability to paste images from the clipboard directly to an issue.  That's is not working here on docs.microsoft.com 😢

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* [Content](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* [Content Source](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: unspecified

**Comment by Narvey** [comment]
If this is a feature suggestion, I don't think it is actually Documentation Feedback. If you want to request the ability to paste images from within Documentation, I think you should use the [Feedback Site for Microsoft Docs](https://msdocs.uservoice.com/forums/364242-general-site-feedback) (also accessible by clicking the "Product Feedback" button under the article).

Note: There is a workaround for getting images into your posts: after submitting your issue, click the # hyperlink at the bottom (for yours it is #2), and edit your post on the GitHub site, leaving the Document Details part alone so that the linking stays intact.

**Comment by spottedmahn** [comment]
Hi @Narvey - good point, it is a feature request.  I'll submit a feedback item.

And yes, good workaround!
