### ISSUE TITLE
AlwaysOn read scale paper problem

### ISSUE THREAD

**Issue by andyyangzhao** [MicrosoftDocs/TeamBlogFeedback#52]
https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/perform-a-planned-manual-failover-of-an-availability-group-sql-server?view=sql-server-2017#ReadScaleOutOnly

HI,
    The above link address paper has syntax error:
ALTER AVAILABILITY GROUP [ag1] 
     SET REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT = 1;

actually, I can't deploy successfully using the paper, could you provide your environment information?

**Comment by andyyangzhao** [comment]
eg: primary replica and secondary replica  is sync or  async?

**Comment by andyyangzhao** [comment]
eg: 
1. primary replica and secondary replica is sync or async?
2. seeding mode 
3. sql server 2017 patch?

**Comment by RobotOverlord** [comment]
I am also having this issue.

**Comment by RobotOverlord** [comment]
Looks like the documentation is wrong, correct syntax is:

ALTER AVAILABILITY GROUP [ag1] 
SET( REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT = 1 );

**Comment by mlottner** [comment]
@andyyangzhao Thanks for taking the time for give us your feedback. 
I've reassigned this issue to the content owner to address your requested change. 
In the future, make sure to leave docs feedback about a specific page on that page to make sure the content/product owner sees it immediately. 
Appreciate your contribution to our community!

**Comment by MashaMSFT** [comment]
Hi @RobotOverlord , thanks for your contribution and feedback! The syntax you have written looks correct. Did you want to update the documentation yourself? This way you'll be credited as a contributor to the documentation. 

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Name your file change and provide a description, if necessary
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page

You can find more information at: https://aka.ms/editsqldocs 

Otherwise, I can process the change on my end. 

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @RobotOverlord, I see the syntax in the article as:

![image](https://user-images.githubusercontent.com/32783170/70194850-c00b9700-16b8-11ea-88d7-0b7c8f3996fa.png)

Which looks the same as what you've listed here - sorry, am I misunderstanding something?

Additionally, @andyyangzhao, my apologies, I am not sure I understand what your question is? 

Step 1 makes the target secondary replica synchronous
The seeding mode is used during AG configuration, but is no longer used after AG is created. 
I don't see any indication that this is any specific patch of SQL Server 2017 so I would assume it will work with RTM and up. Please let me know if you'd like me to research this for you further. 

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @RobotOverlord and @andyyangzhao , it's been some time since we've heard from you. As such, we're going to assume that your question has been addressed and close out this Git Issue. However, should you need anything further, please feel free to leave a comment.

Thanks and hope you both have a wonderful rest of your Monday!
Masha from the SQL Docs team
#please-close
