### ISSUE TITLE
Feedback about "Feedback Mechanisms"

### ISSUE THREAD

**Issue by hobpet** [MicrosoftDocs/TeamBlogFeedback#54]
This article is talking about Livefyre as the feedback mechanism, but -as this feedback proves- it is not there anymore, but in GitHub.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6079073a-0dd9-3b9b-c160-76e0dd525a3c
* Version Independent ID: 631788a5-f4bc-7df0-0540-2a0f67b631de
* Content: [Introducing docs.microsoft.com](https://docs.microsoft.com/en-gb/teamblog/introducing-docs-microsoft-com#feedback)
* Content Source: [teamblog/introducing-docs-microsoft-com.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-docs-microsoft-com.md)
* Service: **unspecified**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by dend** [comment]
This is an older article 😄 Since 2016, we switched to GitHub!

**Comment by hobpet** [comment]
Why did you close this without fixing that paragraph. This article is not marked as outdated, so shall not include invalid information.

**Comment by jantoney** [comment]
This would have been closed because it's a blog post and represents a historical article someone published, not current technical content.
Updates/changes/questions can be viewed in the comments just like I did to find these comments.

The original blog post shouldn't be updated/changed unless it includes technically incorrect information at the time of publishing
